# iOS CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/ios-migrating-from-1-2/ for more details
#
version: 2
jobs:
  build:

    # Specify the Xcode version to use
    macos:
      xcode: "10.0"
    environment:
      LC_ALL: en_US.UTF-8
      LANG: en_US.UTF-8

    steps:
      - checkout

      # Install CocoaPods
      # - run:
      #     name: Install CocoaPods
      #     command: pod install

      - run:
          name: decode Certificates
          context: org-global
          command: 
            echo $Certificates
            base64 -D -o Certificates.p12 <<< $Certificates
      # - run:
      #     name: make Provisioning Profiles directory
      #     command: mkdir -pv ~/Library/MobileDevice/Provisioning\ Profiles/
      # - run:
      #     name: decode Provisioning Profiles
      #     context: org-global
      #     command: base64 -D -o ~/Library/MobileDevice/Provisioning\ Profiles/App_Store.mobileprovision <<< $App_Store_Profile

      # Build the app and run tests
      - run:
          name: Build and run tests
          command: bundle exec fastlane builddebug
      #     environment:
      #       SCAN_DEVICE: iPhone 6
      #       SCAN_SCHEME: WebTests

      # Collect XML test results data to show in the UI,
      # and save the same XML files under test-results folder
      # in the Artifacts tab
      - store_test_results:
          path: test_output/report.xml
      - store_artifacts:
          path: /tmp/test-results
          destination: scan-test-results
      - store_artifacts:
          path: ~/Library/Logs/scan
          destination: scan-logs

